### PR TITLE
This is the first millstone of a ror social media app project

### PR DESCRIPTION
**Pull request by elisha2kyakpo1**
In this millstone, we created an Entity Relation Diagram with primary and foreign keys to show the database mapping

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Changes Required
Hello Team, You progressing well on this milestone. :muscle: 
Some minor changes to make before it can be approved
- [ ] Add the relationship between the user and like tables
- [ ] Use the correct symbols to show the direction of the relationships. For instance the direction between user and friendship table should look like :point_down: 
Screenshot from 2021-02-03 17-35-28

Kindly make the above changes before submitting another review.
### Feel free to contact me on slack [Oloo Moses] incase of doubts or concerns
## Oloo Moses

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello there, nice job you've done on this milestone. However, there are still some mandatory changes you should make in order to move on to the next 🙏😊

<hr>

- [ ] I can see that your ```friendship_sender``` equals the actual ```user_id``` in your Friendship table, but since you're using the identity of a ```user_id``` in the other tables, it'd make more sense if you use the same ```user_id``` in the Friendship table too
- [ ] The relations between the User table and the Friendship table isn't correct. Please refer to the given ERD image and fix yours (as mentioned by the previous code reviewer)
- [ ] The Comment table already has ```created_at``` column, it doesn't make sense to have another one ```posted_at```
- [ ] The Post has the same issue to fix as the Comment table above
- [ ] The Like table has only relations with the ```post_id``` which is the "liked post" and the user who liked it ```user_id```

<hr>

Kindly do the required changes before submitting for a re-review, and remember this is your chance to improve your knowledge and thinking about the associations between your models and the database tables 😊🙏

I wish you the best of luck 🤗👍

**Review by MarilenaRoque — CHANGES_REQUESTED** [review]
Hello Team!!! :rocket:

We're almost there. All the relationships were made correctly. Just some PKs are still missing.

### Changes Required ♻️ 

- [ ] Add PK for the table Like
- [ ] Add PK for the table Comment

Feel free to contact me on Slack for any further information. 😄 
**Happy Coding!** 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

**Review by oloomoses — APPROVED** [review]
# Status: Approved
## Congratulation team! You have done a great job on this milestone. :tada: :clap: :muscle: 
You are free to merge and proceed to the next milestone

**Pull request merged**
